#!/usr/bin/env python
description = """
Searches crunchyroll using dmenu, then
uses livestreamer to open the first result.
"""

import crunchy_search
import argparse
import shlex
import sys
from subprocess import call, Popen, PIPE

def notifier_with_message(notifier, msg):
  return shlex.split(notifier % {'msg': msg})

# Get dmenu
parser = argparse.ArgumentParser(description=description)
parser.add_argument('--dmenu',
    help="how dmenu should be run",
    type=str,
    default='dmenu -p "crunchyroll"')
parser.add_argument('--livestreamer',
    help="""
    how livestreamer should be run.
    The url is added as the last argument.
    """,
    type=str,
    default='livestreamer')
parser.add_argument('--notifier',
    help="""
    how you should be notified.
    Use %%(msg)s where you wish the
    message to appear.
    """,
    type=str,
    default='notify-send -a "dmenu-crunchy-search" "Crunchyroll Search" "%(msg)s"')
args = parser.parse_args()
dmenu = shlex.split(args.dmenu)
livestreamer = shlex.split(args.livestreamer)

# Notifier is not split into args yet
notifier = args.notifier

# Open up dmenu and get its output
dmenu_proc = Popen(dmenu, stdin=PIPE, stdout=PIPE)
selected = dmenu_proc.communicate('')[0].split('\n')[0]

# No selection?
if not selected:
  print('No selection made.')
  sys.exit(1)

# Do the search
try:
  result = crunchy_search.search(selected)
except crunchy_search.SearchError as e:
  call(notifier_with_message(notifier, e))
  sys.exit(1)

# Call livestreamer
call(notifier_with_message(notifier,
  'Now playing %(series)s %(ep_no)d: %(ep_name)s' % result
))

livestreamer.append(result['url'])
call(livestreamer)

